#!/bin/bash
# Set up Firebase app config for the Plain Flags project.
#
# This is step 1 of 2:
#   - Adds Firebase to the GCP project (idempotent)
#   - Creates (or reuses) a Web App named "Plain Flags Dashboard"
#   - Writes API key, App ID and other config to .secrets/firebase.env
#   - Prints manual instructions to initialise Firebase Auth in the console

set -e

if [ ! -f "config/instance-config" ]; then
    echo "Error: config/instance-config not found"
    echo "Run this script from the gcp/infrastructure directory."
    exit 1
fi

source ./config/instance-config

if [ -z "$PROJECT_ID" ] || [ "$PROJECT_ID" = "your-project-id-here" ]; then
    echo "Error: PROJECT_ID not set in config/instance-config"
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "Error: 'jq' is required but not installed."
    echo "Install it with:  sudo apt-get install jq  (Debian/Ubuntu)"
    echo "                  brew install jq            (macOS)"
    exit 1
fi

echo "Setting up Firebase app for GCP project: $PROJECT_ID"

ACCESS_TOKEN=$(gcloud auth print-access-token)
SECRETS_DIR=".secrets"
SECRETS_FILE="$SECRETS_DIR/firebase.env"
TEST_USER_EMAIL="test-runner@${PROJECT_ID}.cloud.test"

CURL_HEADERS=(
    -H "Authorization: Bearer $ACCESS_TOKEN"
    -H "x-goog-user-project: ${PROJECT_ID}"
    -H "Content-Type: application/json"
)

mkdir -p "$SECRETS_DIR"

echo "Adding Firebase to project (safe to run multiple times)..."
ADD_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
    "https://firebase.googleapis.com/v1beta1/projects/${PROJECT_ID}:addFirebase" \
    "${CURL_HEADERS[@]}" \
    -d '{}')

HTTP_CODE=$(echo "$ADD_RESPONSE" | tail -1)
BODY=$(echo "$ADD_RESPONSE" | head -n -1)

if [ "$HTTP_CODE" = "200" ]; then
    echo "✓ Firebase added to project"
elif echo "$BODY" | jq -e '.error.status == "ALREADY_EXISTS"' >/dev/null 2>&1; then
    echo "✓ Firebase already enabled on project"
else
    echo "Warning: Unexpected response when adding Firebase (HTTP $HTTP_CODE):"
    echo "$BODY" | jq . 2>/dev/null || echo "$BODY"
    echo "Continuing..."
fi

echo "Waiting for Firebase project to be ready..."
for i in $(seq 1 12); do
    FB_PROJECT=$(curl -s \
        "https://firebase.googleapis.com/v1beta1/projects/${PROJECT_ID}" \
        "${CURL_HEADERS[@]}")
    FB_STATE=$(echo "$FB_PROJECT" | jq -r '.state // empty')
    if [ "$FB_STATE" = "ACTIVE" ]; then
        echo "✓ Firebase project is active"
        break
    fi
    echo "  Still provisioning... ($((i*5))s)"
    sleep 5
    if [ "$i" = "12" ]; then
        echo "Error: Timed out waiting for Firebase project to become active"
        exit 1
    fi
done

echo "Looking for existing web app..."
APPS_RESPONSE=$(curl -s \
    "https://firebase.googleapis.com/v1beta1/projects/${PROJECT_ID}/webApps" \
    "${CURL_HEADERS[@]}")

APP_ID=$(echo "$APPS_RESPONSE" | jq -r '
    .apps[]?
    | select(.displayName == "Plain Flags Dashboard")
    | .appId' | head -1)

if [ -n "$APP_ID" ]; then
    echo "✓ Found existing web app: $APP_ID"
else
    echo "Creating web app 'Plain Flags Dashboard'..."
    CREATE_RESPONSE=$(curl -s -X POST \
        "https://firebase.googleapis.com/v1beta1/projects/${PROJECT_ID}/webApps" \
        "${CURL_HEADERS[@]}" \
        -d '{"displayName":"Plain Flags Dashboard"}')

    OPERATION_NAME=$(echo "$CREATE_RESPONSE" | jq -r '.name // empty')
    if [ -z "$OPERATION_NAME" ]; then
        echo "Error: Failed to create web app"
        echo "$CREATE_RESPONSE" | jq . 2>/dev/null || echo "$CREATE_RESPONSE"
        exit 1
    fi

    echo "Waiting for web app creation to complete..."
    for i in $(seq 1 12); do
        sleep 5
        OP_RESPONSE=$(curl -s \
            "https://firebase.googleapis.com/v1beta1/${OPERATION_NAME}" \
            "${CURL_HEADERS[@]}")
        DONE=$(echo "$OP_RESPONSE" | jq -r '.done // false')
        if [ "$DONE" = "true" ]; then
            APP_ID=$(echo "$OP_RESPONSE" | jq -r '.response.appId // empty')
            break
        fi
        echo "  Still waiting... ($((i*5))s)"
    done

    if [ -z "$APP_ID" ]; then
        echo "Error: Timed out waiting for web app creation"
        exit 1
    fi
    echo "✓ Web app created: $APP_ID"
fi

echo "Retrieving Firebase SDK config..."
CONFIG=$(curl -s \
    "https://firebase.googleapis.com/v1beta1/projects/${PROJECT_ID}/webApps/${APP_ID}/config" \
    "${CURL_HEADERS[@]}")

API_KEY=$(echo "$CONFIG" | jq -r '.apiKey // empty')
AUTH_DOMAIN=$(echo "$CONFIG" | jq -r '.authDomain // empty')
STORAGE_BUCKET=$(echo "$CONFIG" | jq -r '.storageBucket // empty')
MESSAGING_SENDER_ID=$(echo "$CONFIG" | jq -r '.messagingSenderId // empty')

if [ -z "$API_KEY" ]; then
    echo "Error: Could not retrieve API key from SDK config"
    echo "$CONFIG" | jq . 2>/dev/null || echo "$CONFIG"
    exit 1
fi

echo "✓ Retrieved SDK config"

cat > "$SECRETS_FILE" <<EOF
# Firebase credentials - generated by setup-firebase-app.sh
# DO NOT commit this file to version control
FIREBASE_API_KEY=${API_KEY}
FIREBASE_APP_ID=${APP_ID}
FIREBASE_AUTH_DOMAIN=${AUTH_DOMAIN}
FIREBASE_PROJECT_ID=${PROJECT_ID}
FIREBASE_STORAGE_BUCKET=${STORAGE_BUCKET}
FIREBASE_MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID}
TEST_USER_EMAIL=${TEST_USER_EMAIL}
TEST_USER_PASSWORD=
EOF

chmod 600 "$SECRETS_FILE"

echo ""
echo "✓ Firebase app config written to $SECRETS_FILE"
echo ""
echo "Step 1 complete!"
echo "  API Key:     $API_KEY"
echo "  App ID:      $APP_ID"
echo "  Auth Domain: $AUTH_DOMAIN"
echo ""
echo "Manual step required before continuing:"
echo "  1. Open: https://console.firebase.google.com/project/${PROJECT_ID}/authentication/providers"
echo "  2. Click 'Get started' to initialise Firebase Authentication"
echo "  3. Run: ./setup-firebase-auth.sh"
echo ""
