services:
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - flag-states
    ports:
      - 5001:5001

  flag-management:
    build: ./services/flag-management
    ports:
      - 5000:5000
    environment:
      - JWT_SIGNING_SECRET=eilafefyr8q093478ryvnbchul8934rcnlaa8ry
      - SERVICE_PORT=5000
      - APIKEY=ersafoi89a0ww3n8yrt493ew84yqjwd34y8r09
      - STALE_FLAG_DAYS=20
      - SUPERADMIN_EMAIL=boss@plainflags.com
      - SUPERADMIN_PASSWORD=password
      - DEFAULT_USER_PASSWORD=stop00
      - DISABLE_USER_REGISTRATION=true
    volumes:
      - db-data:/data/:rw

  flag-states:
    build: ./services/flag-states
    environment:
      - SERVICE_PORT=5001
      - APIKEY=ersafoi89a0ww3n8yrt493ew84yqjwd34y8r09
      - MANAGEMENT_WS=ws://flag-management:8080
    volumes:
      - db-data:/data:ro
    depends_on:
      - flag-management
    deploy:
      replicas: 3

  flags-dashboard:
    build: ./dashboard
    ports:
      - 3000:3000
    environment:
      - VITE_API_URL=http://flag-management/api
      - VITE_DISABLE_USER_REGISTRATION=true

volumes:
  db-data: