services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flag-states
    ports:
      - 5001:5001
      - 8081:8081

  flag-management:
    build: ./services/flag-management
    ports:
      - 5000:5000
    environment:
      - JWT_SIGNING_SECRET=jwt_replaceme
      - SERVICE_PORT=5000
      - APIKEY=apikey_replaceme
      - STALE_FLAG_DAYS=20
      - SUPERADMIN_EMAIL=superadmin@email.com
      - SUPERADMIN_PASSWORD=password
      - DEFAULT_USER_PASSWORD=password
      # - DISABLE_USER_REGISTRATION=true
    volumes:
      - db-data:/data/:rw

  flag-states:
    build: ./services/flag-states
    environment:
      - SERVICE_PORT=5001
      - APIKEY=apikey_replaceme
    volumes:
      - db-data:/data:ro
    depends_on:
      - flag-management
    deploy:
      replicas: 3

  flags-dashboard:
    build: ./dashboard
    ports:
      - 3000:3000   # Access the dashboard at port 3000 on the host
    environment:
      - VITE_API_URL=http://flag-management/api
      # - VITE_DISABLE_USER_REGISTRATION=true

volumes:
  db-data: