services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flag-states
    ports:
      - 5001:5001
      - 8081:8081

  db:
    image: postgres:17.4-alpine
    command: postgres -c max_connections=6000
    restart: always
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER=plainflags
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - postgres_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  flag-management:
    depends_on:
      - db
    build: ./services/flag-management
    ports:
      - 5000:5000
    environment:
      - DATABASE_TYPE=pg
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=plainflags
      - DATABASE_USER=plainflags
      - DATABASE_PASSWORD_FILE=/run/secrets/postgres_password
      - DATABASE_POOL_SIZE=512

      - JWT_SIGNING_SECRET_FILE=/run/secrets/jwt_signing_secret
      - SERVICE_PORT=5000
      - APIKEY_FILE=/run/secrets/apikey_mgt
      - STALE_FLAG_DAYS=20
      - SUPERADMIN_PASSWORD_FILE=/run/secrets/superadmin_password
      - DEFAULT_USER_PASSWORD_FILE=/run/secrets/default_user_password
      - SUPERADMIN_EMAIL=boss@plainflags.com
    secrets:
      - jwt_signing_secret
      - superadmin_password
      - default_user_password
      - apikey_mgt
      - postgres_password

  flag-states:
    build: ./services/flag-states
    environment:
      - DATABASE_TYPE=pg
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=plainflags
      - DATABASE_USER=plainflags
      - DATABASE_PASSWORD_FILE=/run/secrets/postgres_password
      - DATABASE_POOL_SIZE=512

      - SERVICE_PORT=5001
      - APIKEY_FILE=/run/secrets/apikey_states
      - CACHE_TTL=1000
    secrets:
      - apikey_states
      - postgres_password
    depends_on:
      - flag-management
      - db
    deploy:
      replicas: 10

  flags-dashboard:
    build: ./dashboard
    ports:
      - 3000:3000   # Access the dashboard at port 3000 on the host
    environment:
      - VITE_API_URL=http://flag-management/api
      # - VITE_DISABLE_USER_REGISTRATION=true

secrets:
  jwt_signing_secret:
    file: ./.secrets/jwt.secret.txt
  superadmin_password:
    file: ./.secrets/password.super.txt
  default_user_password:
    file: ./.secrets/password.user.txt
  apikey_states:
    file: ./.secrets/apikey.states.txt
  apikey_mgt:
    file: ./.secrets/apikey.mgt.txt
  postgres_password:
    file: ./.secrets/password.pg.txt

volumes:
  pgdata: