name: dart_sdk_test
description: Plain Flags Dart SDK tests
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  plain_flags:
    path: ../../../sdk/dart
  http: ^1.5.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
