import { reactRouter } from "@react-router/dev/vite";
import autoprefixer from "autoprefixer";
import tailwindcss from "tailwindcss";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import * as fs from "fs";
import * as path from "path";

export default defineConfig(() => {
    // In dev, load .env.merged (Firebase secrets + local config) into process.env
    // so SSR code in root.tsx can read FIREBASE_* and MANAGEMENT_SERVICE_URL.
    // .env.merged is generated by the "merge-env" pre-launch task in .vscode/tasks.json.
    const mergedEnvPath = path.resolve(__dirname, ".env.merged");
    if (fs.existsSync(mergedEnvPath)) {
        const lines = fs.readFileSync(mergedEnvPath, "utf-8").split("\n");
        for (const line of lines) {
            const match = line.match(/^([^#=\s][^=]*)=(.*)$/);
            if (match) process.env[match[1]] = match[2];
        }
    }

    return {
        css: {
            postcss: {
                plugins: [tailwindcss, autoprefixer],
            },
        },
        plugins: [reactRouter(), tsconfigPaths()],
    };
});